config/routes.rb
OaspCookieOverflow::Application.routes.draw do
  devise_for :users
  
  resources :bid_items
  resources :bid_item_comments, :only=> [:create, :destroy]
  resources :tags, :only=> [:create, :update, :destroy]
  resources :bids, :only=> [:create, :destroy]
  resources :auto_inc_requests, :only=> [:create, :destroy]

  match 'rating/thumbsup' => 'rating#thumbsup', :as => :thumbsup
  
  match 'rating/thumbsdown' => 'rating#thumbsdown', :as => :thumbsdown

  match 'search/bid_item' => 'search#bid_item', :as => :search_bid_items
  
  match 'search/user' => 'search#user', :as => :search_users
  
  match 'inbox' => 'messaging#manage', :as => :inbox
  
  match 'messaging/create' => 'messaging#create', :as => :message_create
  
  match 'messaging/read/:id' => 'messaging#read', :as => :read_message
  
  match 'admin/select_user' => 'admin#select_user', :as => :admin_select_user
  match 'admin/support' => 'admin#mail', :as => :admin_support
  match 'admin/send_mail' => 'admin#send_mail', :as => :admin_mail
  match 'admin/become_seller' => 'admin#become_seller', :as => :become_seller
  match 'admin/edit_user_permissions' => 'admin#edit_user_permissions', :as => :admin_edit_user
  match 'admin/change_user_permissions' => 'admin#change_user_permissions', :as => :admin_edit_user_commit
  
  
  root :to => "bid_items#index"
  

end

app/views/admin/edit_user_permissions.html.erb
<% content_for :left_column do %>
	<h3>Recent Comments</h3>
	<% @user.recent_comments(5).each do |comment| %>
		<%= render :partial => "bid_item_comments/comment_profile_large", :locals => {:comment => comment, :show_comment_item => true} %>
	<% end %>
<% end %>
<h1>Manage: <%= @user.email %> </h1>
<%= form_tag(admin_edit_user_commit_path, :method => :post) do %>
  	<%= select_tag "roles", options_for_select(Role.all.collect { |r| r.title }, @user.roles.collect { |r| r.title }), :multiple => true %><br />
	<%= hidden_field_tag "user_id", @user.id %>
	<%= submit_tag "Change Roles" %>
<% end -%>

<% if @user.recent_auctions.size == 0 %>
	<h3>This user has not posted any items for auction</h3>
<% else %>
  <h3>Recent auctions by this user</h3>
  <% @user.recent_auctions.each_with_index do |bid_item, index| %>
	<%= render :partial => "bid_items/bid_item_profile_large", :locals => { :bid_item => bid_item, :index => index } %>
  <% end %>		
<% end %>

<% content_for :right_column do %>
	<h3>Recent Bids</h3>
	<% @user.recent_bids(10).each do |bid| %>
		<%= render :partial => "bids/bid_item_profile", :locals => {:bid => bid, :show_bid_item => true} %>
	<% end %>
<% end %>

app/views/admin/mail.html.erb
<%= form_tag(admin_mail_path, :method => :post) do |f| %>
	<%= text_area_tag :message %>
	<%= submit_tag "Create Support Ticket" %>
<% end %>

app/views/admin/select_user.html.erb
<%= form_tag(admin_edit_user_path, :method => :post) do |f| %>
	<%= select_tag "user_id", options_from_collection_for_select(@users, "id", "email") %>
	<%= submit_tag "Select User"  %>
<% end %>