config/routes.rb
OaspCookieOverflow::Application.routes.draw do
  devise_for :users
  
  resources :bid_items
  resources :bid_item_comments, :only=> [:create, :destroy]
  resources :tags, :only=> [:create, :update, :destroy]
  resources :bids, :only=> [:create, :destroy]
  resources :auto_inc_requests, :only=> [:create, :destroy]

  match 'rating/thumbsup' => 'rating#thumbsup', :as => :thumbsup
  
  match 'rating/thumbsdown' => 'rating#thumbsdown', :as => :thumbsdown

  match 'search/bid_item' => 'search#bid_item', :as => :search_bid_items
  
  match 'search/user' => 'search#user', :as => :search_users
  
  match 'inbox' => 'messaging#manage', :as => :inbox
  
  match 'messaging/create' => 'messaging#create', :as => :message_create
  
  match 'messaging/read/:id' => 'messaging#read', :as => :read_message
  
  match 'admin/select_user' => 'admin#select_user', :as => :admin_select_user
  match 'admin/support' => 'admin#mail', :as => :admin_support
  match 'admin/send_mail' => 'admin#send_mail', :as => :admin_mail
  match 'admin/become_seller' => 'admin#become_seller', :as => :become_seller
  match 'admin/edit_user_permissions' => 'admin#edit_user_permissions', :as => :admin_edit_user
  match 'admin/change_user_permissions' => 'admin#change_user_permissions', :as => :admin_edit_user_commit
  
  
  root :to => "bid_items#index"
  

end

app/controllers/messaging_controller.rb
class MessagingController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  
  def manage
    @user = current_user 
  end

  def create
    message = Message.new
    message.from_user = User.find(params[:from_user]) if params[:from_user]
    message.to_user = User.find(params[:to_user]) if params[:to_user]
    message.message = params[:message] if !params[:message].nil?
    if message.save
      redirect_to(inbox_path, :notice => "Message was sent")
    else
      redirect_to(inbox_path, :notice => "Message could not be sent")
    end
  end
  
  def read
    message = Message.find(params[:id])
    authorize! :update, message 
    message.unread = false
    message.save
    redirect_to(inbox_path, :notice => "Message was marked as read")
  end
end

app/helpers/messaging_helper.rb
module MessagingHelper
end

app/views/messaging/_message_profile.html.erb
<div class="message_profile">
	<% user = (!!incoming) ? message.from_user : message.to_user %>
	<%= image_tag "#{gravatar(user.email)}?s=45" %> <b><%= user.email %></b><br />
	<b>said...</b>
	<p><%= message.message %></p>
	<i><%= time_ago_in_words(message.created_at) %> ago...</i><br />
	<% if message.unread && can?(:update, message) %>
		<%= link_to("Mark as read", read_message_path(:id => message.id)) %>
	<% end %>
</div>

app/views/messaging/manage.html.erb
<script type="text/javascript" charset="utf-8">
	$(document).ready(function(){
		$("#user_search_submit").click(function(){
			$.post("<%= search_users_path %>", {q : $('#user_search_input').val()}, function(data) {
				var html = "";
				for (var i=0; i < data.length; i++) {
					html += "<option value='" + data[i].value + "'>" + data[i].name + "</option>"
				};
				$("#to_user").html(html);
			});
			$("#to_user").html("");
			$("#user_search_input").val("");
		});
	});
</script>
<% content_for :left_column do %>
	<h3>Sent Messages</h3>
	<% @user.sent_messages.each do |m| %>
		<%= render :partial => "messaging/message_profile", :locals => {:message => m, :incoming => false} %>
	<% end %>
<% end %>
<div id="message_compose">
	<h3>Search User</h3>
	<input type="text" placeholder="User..." id="user_search_input" >
	<input type="submit" value="Search User" id="user_search_submit"><br /><br />
	<%= form_tag(message_create_path, :method => :post) do %>
		<h3>Users</h3>
		To: <select name="to_user" id="to_user"></select><br />
		Message: <br />
		<input type="hidden" name="from_user" value="<%= current_user.id.to_s %>" id="from_user">
		<textarea id="message" name="message"></textarea>
		<input type="submit" value="Send">
	<% end %>
</div>

<h3>Unread Messages</h3>
<% @user.unread_messages.each do |m| %>
	<%= render :partial => "messaging/message_profile", :locals => {:message => m, :incoming => true} %>
<% end %>

<% content_for :right_column do %>
	<h3>Read Messages</h3>
	<% @user.read_messages.each do |m| %>
		<%= render :partial => "messaging/message_profile", :locals => {:message => m, :incoming => false} %>
	<% end %>
<% end %>