config/routes.rb
OaspCookieOverflow::Application.routes.draw do
  devise_for :users
  
  resources :bid_items
  resources :bid_item_comments, :only=> [:create, :destroy]
  resources :tags, :only=> [:create, :update, :destroy]
  resources :bids, :only=> [:create, :destroy]
  resources :auto_inc_requests, :only=> [:create, :destroy]

  match 'rating/thumbsup' => 'rating#thumbsup', :as => :thumbsup
  
  match 'rating/thumbsdown' => 'rating#thumbsdown', :as => :thumbsdown

  match 'search/bid_item' => 'search#bid_item', :as => :search_bid_items
  
  match 'search/user' => 'search#user', :as => :search_users
  
  match 'inbox' => 'messaging#manage', :as => :inbox
  
  match 'messaging/create' => 'messaging#create', :as => :message_create
  
  match 'messaging/read/:id' => 'messaging#read', :as => :read_message
  
  match 'admin/select_user' => 'admin#select_user', :as => :admin_select_user
  match 'admin/support' => 'admin#mail', :as => :admin_support
  match 'admin/send_mail' => 'admin#send_mail', :as => :admin_mail
  match 'admin/become_seller' => 'admin#become_seller', :as => :become_seller
  match 'admin/edit_user_permissions' => 'admin#edit_user_permissions', :as => :admin_edit_user
  match 'admin/change_user_permissions' => 'admin#change_user_permissions', :as => :admin_edit_user_commit
  
  
  root :to => "bid_items#index"
  

end

app/models/bid_item.rb
class BidItem < ActiveRecord::Base

  attr_accessible :title, :body, :picture, :starting_price, :end_time, :next_bid_delta
  validates_presence_of :title, :user_id, :starting_price
  validates_numericality_of :starting_price, :integer_only => true, :gt => 0

  validates_attachment_size :picture, :less_than => 2.megabytes
  validates_attachment_content_type :picture, :content_type => ['image/jpeg', 'image/png']
  
  validates_presence_of :end_time
  validates_presence_of :next_bid_delta
  
  belongs_to :user
  has_many :bid_item_comments
  has_many :auto_inc_requests
  
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_many :bids
  has_and_belongs_to_many :tags
  
  after_create :setup_bid_finishing_tasks
  
  after_save :notify_bidders_of_modifications

  before_destroy :notify_bidders_of_deletion

  define_index do
    indexes title
    indexes body
  end
  
  def highest_bid
    bids.find(:first, :order => "bid_amount desc")
  end
  
  def latest_bids(number=10)
    bids.find(:all, :order => "bid_amount desc", :limit => number)
  end
  
  def minimum_bidding_price
    if highest_bid.nil?
      starting_price
    else
      highest_bid.bid_amount + next_bid_delta
    end
  end
  
  def is_open?
    DateTime.now < end_time
  end
  
  def setup_bid_finishing_tasks
    Resque.enqueue_at(end_time, MailWinner, id)
    Resque.enqueue_at(end_time, MailSeller, id)
  end
  
  def notify_bidders_of_modifications
    Resque.enqueue(NotifyBiddersOfModifications, id, "modified")
  end
  
  def notify_bidders_of_deletion
    mails = bids.each.collect { |b| b.user.email }.uniq
    Resque.enqueue(NotifyBiddersOfDeletion, "#{title}: #{body}", mails)
  end
end

app/controllers/bid_items_controller.rb
class BidItemsController < ApplicationController
  #before_filter :authenticate_user!, :except => [:index, :show]
  
  # GET /bid_items
  # GET /bid_items.xml
  def index
    @bid_items = BidItem.all
    authorize! :read, @bid_items
  end

  # GET /bid_items/1
  # GET /bid_items/1.xml
  def show
    @bid_item = BidItem.find(params[:id])
    if current_user
      @auto_inc_req = AutoIncRequest.find_by_user_id_and_bid_item_id(current_user.id, @bid_item.id) if current_user
    else
      @auto_inc_req = nil
    end
    authorize! :read, @bid_item
  end

  # GET /bid_items/new
  # GET /bid_items/new.xml
  def new
    @bid_item = BidItem.new
    authorize! :create, @bid_item
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bid_item }
    end
  end

  # GET /bid_items/1/edit
  def edit
    @bid_item = BidItem.find(params[:id])
    authorize! :update, @bid_item
  end

  # POST /bid_items
  # POST /bid_items.xml
  def create
    @bid_item = BidItem.new(params[:bid_item])
    @bid_item.user = current_user
    authorize! :create, @bid_item
    respond_to do |format|
      if @bid_item.save
        format.html { redirect_to(@bid_item, :notice => 'BidItem was successfully created.') }
        format.xml  { render :xml => @bid_item, :status => :created, :location => @bid_item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bid_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bid_items/1
  # PUT /bid_items/1.xml
  def update
    @bid_item = BidItem.find(params[:id])
    authorize! :update, @bid_item
    respond_to do |format|
      if @bid_item.update_attributes(params[:bid_item])
        format.html { redirect_to(@bid_item, :notice => 'BidItem was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bid_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bid_items/1
  # DELETE /bid_items/1.xml
  def destroy
    @bid_item = BidItem.find(params[:id])
    authorize! :destroy, @bid_item
    @bid_item.destroy    
    respond_to do |format|
      format.html { redirect_to(bid_items_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/bid_items_helper.rb
module BidItemsHelper
end

app/views/bid_items/_bid_item_profile_large.html.erb
<div class="bid_item_profile_large">
    <h2><%=h bid_item.title %></h2>
	<%= link_to image_tag(bid_item.picture.url(:medium), :width => "140px", :style => "float: #{ (index%2 == 0) ? 'left' : 'right'}"), bid_item %>
    <%=h truncate(bid_item.body, :length => 200) %>
	<div class="links">
		<%= link_to 'Show', bid_item %>&nbsp;&nbsp;
	    <%= link_to 'Edit', edit_bid_item_path(bid_item) if can? :update, bid_item %>&nbsp;&nbsp;
	    <%= (link_to 'Destroy', bid_item, :confirm => 'Are you sure?', :method => :delete) if can? :destroy, bid_item %>
	</div>
</div>

app/views/bid_items/_bid_item_profile_small.html.erb
<div class="bid_item_profile_small <%= position %>">
	<%= link_to(image_tag(item.picture.url(:thumb)), item) %>
	<h3><%= item.title %></h3>
</div>

app/views/bid_items/edit.html.erb
<h1>Editing bid item</h1>

<%= form_for(@bid_item) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.label :picture, "You can submit a picture here" %><br />
    <%= f.file_field :picture %>
  </p>

  <p>
    <%= f.label :starting_price %><br />
    <%= f.text_field :starting_price %>
  </p>

  <p>
    <%= f.label :next_bid_delta, "Minimum price difference between bids" %><br />
    <%= f.text_field :next_bid_delta %>
  </p>

  <p>
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

 <%= form_tag(:controller => :tags, :action => :create, :method => :post) do %>
  <p>
    <%= text_field_tag  "title" %>
  </p>
    <%= hidden_field_tag("bid_item_id", @bid_item.id)  %>
  <p>
    <%= submit_tag 'Add Tag' %>
  </p>
 <% end %>

<%= link_to 'Show', @bid_item %>&nbsp;&nbsp;
<%= link_to 'Back', bid_items_path %>

app/views/bid_items/index.html.erb
<% content_for :left_column do %>
	<h1>Recent Bids</h1>
	<% if !Bid.most_recent.blank? %>
		<% Bid.most_recent.each do |bid| %>
			<%= render :partial => "bids/bid_item_profile", :locals => {:bid => bid, :show_bid_item => true} %>
		<% end %>
	<% end %>
<% end %>

<h1>All Bid Items</h1>

<% @bid_items.each_with_index do |bid_item, index| %>
    <%= render :partial => "bid_item_profile_large", :locals => { :bid_item => bid_item, :index => index } %>
<% end %>

<% if can? :create, BidItem %>
	<%= link_to 'Add new bid item', new_bid_item_path %>
<% else %>
	<h3>Only sellers can create bid items</h3>
	<% if current_user %>
		<%= form_tag(:action => "become_seller", :controller => "admin", :method => :post) do |f| %>
			<%= submit_tag "Become a seller" %>
		<% end %>
	<% end %>
<% end %>

<% content_for :right_column do %>
	<h1>Hot items</h1>
	<% if !Bid.most_recent.blank? %>
		<% for item in Bid.most_recent %>
			<% if !item.bid_item.nil? %>
		  		<%= render :partial => "bid_item_profile_small", :locals => {:item => item.bid_item, :position => cycle('left', 'right')} %>  
			<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/bid_items/index.mobile.erb
<ul data-role="listview">
	<% @bid_items.each_with_index do |bid_item, index| %>
		<li><%= link_to(bid_item.title, bid_item) %></li>
	<% end %>
</ul>

app/views/bid_items/new.html.erb
<h1>Add a new item for bidding</h1>

<%= form_for(@bid_item, :html => {:multipart => true}) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.label :picture, "You can submit a picture here" %><br />
    <%= f.file_field :picture %>
  </p>

  <p>
    <%= f.label :starting_price %><br />
    <%= f.text_field :starting_price, :value => 0 %>
  </p>

  <p>
    <%= f.label :next_bid_delta, "Minimum price difference between bids" %><br />
    <%= f.text_field :next_bid_delta, :value => 10 %>
  </p>

  <p>
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time, :default => 2.days.from_now %>
  </p>
  
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>
<%= link_to 'Back', bid_items_path %>

app/views/bid_items/show.html.erb
<% content_for :left_column do %>
	<div id="top_bidder_section">
		<% if !@bid_item.highest_bid.nil? %>
			<h3>Current Highest Bidder</h3>
		  	<%= render :partial => "bids/bid_item_profile", :locals => {:bid => @bid_item.highest_bid, :show_bid_item => false} %>
		<% end %>
	</div>
	<div id="bid_section">
		<p>Bidding Started at <span class="currency">$<%=h @bid_item.starting_price %></span></p>
		
		<% if @bid_item.is_open? %>
			<h4>Hurry, this bid will end <%= distance_of_time_in_words(Time.now, @bid_item.end_time) %> from now.</h4>
			<% if can?(:create, Bid) %>
				<%= form_for(@bid_item.bids.build) do |f| %>
					<p>
					  <%= f.text_field(:bid_amount, :value => @bid_item.minimum_bidding_price) %>
					</p>
					<%= hidden_field_tag :bid_item_id, @bid_item.id %>
					<p>
					  <%= f.submit('Bid Now') %>
					</p>
				<% end %>
				<h3>The minimum bid is $<%= @bid_item.minimum_bidding_price %></h3>
				<h3>Rules:</h3>
				<ul>
					<li>
						Bidding Starts At $<%= @bid_item.starting_price %>
					</li>
					<li>
						Minimum Bid Difference $<%= @bid_item.next_bid_delta %>
					</li>
				</ul>
			<% else %>
				<p>Sign up to start bidding.</p>
			<% end %>
	    <% else %>
			<h3>Sorry, bidding for this item ended <%= time_ago_in_words(@bid_item.end_time) %> ago.</h3>
		<% end %>
		<% if @bid_item.bids.size != 0 %>
		  	<h3>Bidding History</h3>
			<% @bid_item.latest_bids.each do |bid| %>
				<%= render :partial => "bids/bid_item_profile", :locals => {:bid => bid, :show_bid_item => false} %>
			<% end %>
		<% else %>
			<p>No one has bid on this item</p>
		<% end %>
	</div>
<% end %>

<h2><%=h @bid_item.title %></h2>
<div class="bid_item_profile_big">
	<%=image_tag @bid_item.picture.url(:medium), :style => "float: right; width: 250px;" %><br/>
	<%=h @bid_item.body %>	
</div>
<div class="comments_profile">
	This item was added for auction by <%= @bid_item.user.email %> <%= render :partial => "users/karma_manager", :locals => {:user => @bid_item.user} %>
</div>
<div id="links">
	<% if can? :update, @bid_item %>
		<%= link_to 'Edit', edit_bid_item_path(@bid_item) %>&nbsp;&nbsp;
	<% end %>
	<% if can? :destroy, @bid_item %>
		<%= link_to "Delete", @bid_item, :method => :delete, :confirm => "Are you sure?" %>&nbsp;&nbsp;
	<% end %>
	<%= link_to 'Back', bid_items_path %>	
</div>

<hr />
<% if @bid_item.tags.size != 0 %>
	<b>Tags: </b>
	<% for tag in @bid_item.tags do %>
		<%=h tag.title %>&nbsp;&nbsp;
	<% end %>
<% else %>
	<p>This listing has no tags...</p>
<% end %>

<hr />
<h3>Comments</h3>
	
  <% for comment in @bid_item.bid_item_comments do %>
	  <%= render :partial => "bid_item_comments/comment_profile_large", :locals => {:comment => comment, :show_comment_item => false} %>
  <% end %>

<% if can? :create, BidItemComment %>
	<%= form_for(BidItemComment.new) do |f| %>
	    <%= f.label :body %><br />
	    <%= f.text_area :body %>
		<%= f.hidden_field(:bid_item_id, :value => @bid_item.id)  %>
	    <%= f.submit 'Add a new comment' %>
	<% end %>
<% else %>
	<p>You cannot add comments. Try logging in.</p>
<% end %>



<% content_for :right_column do %>
	<h3>Automatic Bidder</h3>
	<% if @auto_inc_req %>
		<p>An automatic increment wizard has already been setup. The bid ceiling is <b>$<%= @auto_inc_req.maximum_amount %></b></p>
		<p><%= link_to "Delete Automatic Bidder", @auto_inc_req, :method => :delete, :confirm => "Are you sure you want to remove the automatic bidder?" %></p>
	<% else %>
		<% if current_user %>
			<%= form_for(AutoIncRequest.new) do |f| %>
				<%= f.hidden_field :user_id, :value => current_user.id %>
				<%= f.hidden_field :bid_item_id, :value => @bid_item.id %>
				<%= f.text_field :maximum_amount, :value => @bid_item.minimum_bidding_price + 100 %>
				<%= f.submit "Setup Automatic Bidder" %>
			<% end %>
		<% else %>
			<h3>Login to setup the automatic bidder on this item.</h3>
		<% end %>
	<% end %>
	<h3>Other items by this seller</h3>
	<% @bid_item.user.bid_items.each_with_index do |item, index| %>
		<%= render :partial => "bid_item_profile_small", :locals => {:item => item, :position => (index % 2 == 1) ? 'left' : 'right'} %>
	<% end %>
<% end %>

app/views/bid_items/show.mobile.erb
<div>
	<h2><%=h @bid_item.title %></h2>
	<p><%=image_tag @bid_item.picture.url(:medium), :style => "align: center" %><br/>
	<%=h @bid_item.body %></p>
	

	<% if !@bid_item.highest_bid.nil? %>
		<h3>Current Highest Bidder</h3>
		<%= image_tag("#{gravatar(@bid_item.highest_bid.user)}?s=40") %>
		<p>Bid Amount: $<%= @bid_item.highest_bid.bid_amount %> by <%= @bid_item.highest_bid.user.email %></p>
	<% else %>
		<h3>No one has bid on this item</h3>
	<% end %>

	<% if @bid_item.is_open? %>
		<ul data-role="listview" data-inset="true">
			<li data-role="list-divider">
				Bidding Rules
			</li>
			<li>The minimum bid is now $<%= @bid_item.minimum_bidding_price %></li>
			<li>Bidding Starts At $<%= @bid_item.starting_price %></li>
			<li>Minimum Bid Difference $<%= @bid_item.next_bid_delta %></li>
			<li>Hurry, this bid will end <%= distance_of_time_in_words(Time.now, @bid_item.end_time) %> from now.</li>
		</ul>
		<% if can?(:create, Bid) %>
			<%= form_for(@bid_item.bids.build) do |f| %>
				<p>
				  $ <%= f.text_field(:bid_amount, :value => @bid_item.minimum_bidding_price) %>
				</p>
				<%= hidden_field_tag :bid_item_id, @bid_item.id %>
				<p>
				  <%= f.submit('Bid Now') %>
				</p>
			<% end %>
			
		<% else %>
			<p>Sign up to start bidding.</p>
		<% end %>
    <% else %>
		<h3>Sorry, bidding for this item ended <%= time_ago_in_words(@bid_item.end_time) %> ago.</h3>
	<% end %>
	
		<ul data-role="listview" data-inset="true">
			<li data-role="list-divider">Comments</li>
		<% for comment in @bid_item.bid_item_comments do %>
		    <li>
				<%= image_tag(gravatar(comment.user.email) + "?s=35", :style => "padding: 10px") %>
				<div style="padding-left: 50px">
					<h3><%= comment.user.email %> says...</h3>
					<p><%= comment.body %></p>
				</div>
			</li>
		<% end %>
		</ul>
		<% if can? :create, BidItemComment %>
			<%= form_for(BidItemComment.new) do |f| %>
			    <%= f.label :body %><br />
			    <%= f.text_area :body %>
				<%= f.hidden_field(:bid_item_id, :value => @bid_item.id)  %>
			    <%= f.submit 'Add a new comment' %>
			<% end %>
		<% else %>
			<p>You cannot add comments. Try logging in.</p>
		<% end %>		


</div>